### ISSUE TITLE
Enable logging if environment variable set

### ISSUE THREAD

**Issue by letmaik** [microsoft/Azure-DCAP-Client#102]
To diagnose issues it would be convenient if the internal printf logging could be enabled if some AZDCAP_LOGGING=1 environment variable or similar is set. Currently, the library has to be rebuilt to enable logging. This is for Linux. I'm aware that on Windows some event logging takes place already, though the same printf approach would make sense for convenience.

**Comment by letmaik** [comment]
I'm afraid not as I don't manage the DCAP library myself but rather use it via Open Enclave. I would consider the proposed environment variable to be something like [LD_DEBUG](http://www.bnikolic.co.uk/blog/linux-ld-debug.html) which works the same way and is very useful without touching the code.

**Comment by deschuma** [comment]
OESDK sets the logging callback - I believe all of that logging is managed via the OE_LOG_LEVEL environment variable already (including the messages from the az dcap library). 

Regardless I think it would be nice to be able to control the logging independently via a separate environment variable but let me know what you think

**Comment by letmaik** [comment]
Ah I didn't realize. So OE turns on DCAP logging if the log level is at least INFO, which doesn't print out too much extra stuff, but still quite a bit. I think I'm still interested in a separate environment variable for two reasons: 1) the DCAP client does network requests and I'm really interested to see them and only them (I'm not interested in general OE logging), and 2) the DCAP client can also be used outside OE.

**Comment by deschuma** [comment]
Thanks! I agree a separate environment variable would be useful for development

**Comment by deschuma** [comment]
I've opened a PR for this - I opted to prefer the logging callback over the stdout printing in the case that the logging callback is set. For OE SDK, it seems the logging callback is only set if OE_LOG_LEVEL is set. This prevent duplicate messages from being printed in the case both environment variables are set. Environment variable is listed in the readme in the PR.
