### ISSUE TITLE
Error log if AZDCAP_DEBUG_LOG_LEVEL env var is not set

### ISSUE THREAD

**Issue by jumaffre** [microsoft/Azure-DCAP-Client#114]
If the `AZDCAP_DEBUG_LOG_LEVEL` environment is not set, the following error log is printed: 
`Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'`

I believe this is undesirable behaviour and the library should set a sensible default value for the log level that _could_ be overridden with `AZDCAP_DEBUG_LOG_LEVEL`.

**Comment by achamayou** [comment]
That should be a warning/info, it's definitely not an error. Filed https://github.com/microsoft/Azure-DCAP-Client/pull/115 for the typo.
