### ISSUE TITLE
MS Azure DCAP VMs and Graphene: mismatch in Graphene and AESM expectations

### ISSUE THREAD

**Issue by dimakuv** [microsoft/Azure-DCAP-Client#129]
When trying to run a sample application with MS Azure DCAP-based VM (see https://docs.microsoft.com/en-us/azure/confidential-computing/quick-create-portal), we experience the following issue: https://github.com/oscarlab/graphene/issues/2062.

Graphene is an SGX runtime to run unmodified Linux applications (https://github.com/oscarlab/graphene). Graphene's remote attestation capabilities were always tested against the classic Intel SGX DCAP attestation on bare-metal local machines and not in the MS Azure VM. When testing with MS Azure SGX-enabled DCAP-based VM, we see this:
```sh
$ ... running a Graphene SGX remote attestation (RA) sample ...
aesm_service returned error: 1    # from what I understand, this is simply " AESM_UNEXPECTED_ERROR"
```

What happens behind the scenes in Graphene is as follows:
1. The SGX enclave starts
2. Graphene notices that the app wants to do SGX RA at some point, so Graphene starts initialization of SGX RA
3. As part of this initialization of RA, Graphene must retrieve TargetInfo of the Quoting Enclave (QE)
4. Graphene talks to AESM daemon on the `/var/run/aesmd/aesm.socket` Unix domain socket
5. The message that Graphene sends to the AESM is `InitQuoteExRequest` in Protobuf "proto2" format
6. The message that Graphene expects in response from AESM is `InitQuoteExResponse` in Protobuf "proto2" format
7. Graphene does some light checks that the AESM-provided QE TargetInfo makes sense and memorizes this TargetInfo for future use by the app (in `GetQuoteExRequest` messages to AESM)

So Graphene sidesteps the DCAP shared libraries for all these steps (for self-contained code reasons). Here are some relevant sources in Graphene:
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/quote/aesm.proto -- protobuf format of the AESM messages
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c -- code to communicate with AESM
    - https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L19 -- hard-coded attestation key of Intel QE (could this be an issue?)
    - https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L126 -- function to retrieve QE TargetInfo (implements steps 3-7)
    - https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L159 -- start of the initialization logic for non-EPID (i.e. DCAP) attestation
    - https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L164 -- initializing the InitQuoteExRequest message to AESM (could the values there be an issue?)
    - https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L183 -- examining the InitQuoteExResponse message from AESM (maybe we incorrectly parse it?)

Graphene fails on the MS Azure DCAP VM somewhere at steps 6-7. I can't figure out why the AESM daemon on the MS Azure VM doesn't like Graphene's `InitQuoteExRequest` message (or why doesn't Graphene like the returned `InitQuoteExResponse`). Maybe Microsoft VMs use their own QE implementation and the attestation key is different (from the classic Intel one)?

I looked through the MS Azure DCAP code, but it doesn't look relevant to my issue: https://github.com/microsoft/Azure-DCAP-Client/src. Any help or forwarding to the right people will be greatly appreciated!

**Comment by dimakuv** [comment]
An update: I found out that the EPID attestation scheme works on my Azure CC VM instance!

My instance is `DC1s_v2` in `West US`.

I'm not sure how to explain it. I always thought that these CC instances use DCAP/ECDSA remote attestation instead of the older EPID remote attestation. Or are there somehow both attestation schemes possible?

For more info, you can check my other post: https://github.com/oscarlab/graphene/issues/2062#issuecomment-769776784.

**Comment by deschuma** [comment]
Were you able to resolve this issue? Otherwise I would recommend filing an issue with the OE SDK project as I don't think this is Azure DCAP Client specific. https://github.com/openenclave/openenclave

**Comment by dimakuv** [comment]
Yes, @deschuma, we resolved the issues. There was some MS Azure magic involved, but in the end it worked. Thanks.
