### ISSUE TITLE
SGX-DCAP Quote-Verification fails with out-proc mode generated quote 

### ISSUE THREAD

**Issue by veenasai2** [microsoft/Azure-DCAP-Client#142]
Hi ,

I am using AKS --enable-sgxquotehelper plugin to generate sgx quote for https://github.com/intel/SGXDataCenterAttestationPrimitives/  Samples. The quote generation is successful, but quote verification fails with the error: "Error: App: sgx_qv_verify_quote failed: 0xe022". [SGX_QL_PCK_CERT_CHAIN_ERROR] : this implies there was an error verifying the PCK Cert signature chain including PCK Cert revocation. 

**Setup:** Two Containers running as part of AKS cluster. 
**Service Container 1:** dcap-pccs service is running and is reachable by Container 2
**Application Container 2:** Quote generation and verification is happening for SGXDataCenterAttestationPrimitives/Samples

1. This error is visible only with the quote generated using out-proc mode, where aesmd service is generating the quote.
2. I am successfully able to verify the quote generated using in-proc mode.
3. Also, if I generate out-proc mode quote at my local system [not as part of Azure VM] and copy the quote into Application container 2 image, I am successfully able to verify the quote. 

So, looks like the quote generated using AKS --enable-sgxquotehelper plugin, is not verifiable. 
 
Therefore, I wanted to check, if we need to download some specific certificate , in order to verify the out-proc quote generated using Azure sgxquotehelper?

Link that I followed: https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-out-of-proc-attestation

Thanks.

**Comment by veenasai2** [comment]
**Addition INfo**: The API version for PCS collatoral is V3 in my setup. If sgx-quotehelper is providing the collatoral in V2 or V1 API format, that can also be a possible reason for this failure.

**Comment by veenasai2** [comment]
Hi, Any updates on this issue?

**Comment by szutshi-msft** [comment]
> Hi, Any updates on this issue?

Hi veenasai -- I'm not sure I have the answer to your problem but one thing that may help identify it based on your comments is what version of the DCAP you are running and whether the default collateral version is set to v3 within that release. DCAP was recently released with v3 as default up from v2 and therefore wouldn't serve v3 certs until then.

**Comment by veenasai2** [comment]
Thanks szutshi-msft. Based on your answer, my understanding is that the collateral version used fo sgxquotehelper plugin is still V2.  Can you please help me by answering following questions ?

1. Are there any plans to upgrade to V3 soon for sgxquotehelper?
2. Is there any open-source github repo for sgxquotehelper that I can refer to?
3. Is there any sgx quote verifier* plugin that Azure provides with AKS? 

Thanks again for your kind help.

**Comment by veenasai2** [comment]
Hi ,

As per my understanding azure-dcap-client provides azure version of sgx quote provider libraray and we get libdcap_quoteprov.so. The quote provider library contacts azure caching server for generating and verfying the collateral (i.e., cert chain from Intel PCS).

That being said, my question is:
How sgxquotehelper makes a call to az-dcap-client during out-proc quote generation?

Because even if I don't install az-dcap-client as part of my dockerfile, I am still able to generate out-proc sgx quote. 
So, looks like the sgxquotehelper daemon internally makes a call to az-dcap-client. 

Any clarifications would really help!!!

Thanks.

**Comment by veenasai2** [comment]
@yentsanglee thanks for your reply.

Yes, I am using AKS cluster with confidential compute node VM and sgxquotehelper plugin.

**Comment by veenasai2** [comment]
@yentsanglee  will you be able to point me to any sgxquotehelper plugin document by Microsoft ? I am aware of only this link https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-out-of-proc-attestation.

**Comment by yentsanglee** [comment]
@veenasai2 If you can decode the problematic PCK certificate, you will be able to tell its collateral version. As described in issue #135, version field in collateral struct is 1 which means the CRL is PEM decoded. SGX QvL/QvE should still honor collateral version 1 though. If you can set up to trace into SGX quote verification library, it'd be easier to root cause.

Another option is to completely remove SGX default QPL and use only Azure-DCAP-Client as QPL, if your attester run in Azure cloud.

I am not familiar with sgx quote helper. I will let others comment on it.

**Comment by swamymsft** [comment]
@veenasai2 To scope down the issue if it is specific to the sgxquotehelper or not, were you able to manage getting the quote verification working with inproc mode? 

At highlevel, sgxquotehelper is basically a daemonset the encapsulates the Intel AESM service. So in the out-of-proc mode it uses AESM for all the quote generation.

The sgxquotehelper is mainly used for out-of-proc quote generation. When the environment variable SGX_AESM_ADDR is set to 1 for a container the quote generation call will go to AESM through libsgx-quote-ex.so. The quote verification still happen through the Azure DCAP  installed within the container irrespective of in-proc or out-of-proc. I'm wondering if you are hitting this issue. To confirm this, you can install the Azure DCAP inside the container and check if the verification works.

**Comment by veenasai2** [comment]
Thanks @yentsanglee , I will try your suggestions. 

@swamymsft With az-dcap-client both in-proc and out-proc quote verification was working, that means underneath the azure version of qpl is providing the collateral by consulting the azure caching server https://global.acccache.azure.net/sgx/certificates . But I wanted to make the verification happen using sgx qpl and the sgx dcap caching server (I will call it my_pccs, that I launched in one of the AKS container).

Supringly in-proc quote verification was working with sgx qpl(latest) and my_pccs (latest, V3 type), but I got error, when trying to verify the out-proc quote that was generated by azure sgx-quote-helper (i.e., azure provided aesm talking to az-dcap-client for quote generation).  

So, my guess was the az-dcap-client which is installed on the azure VM (on which the AKS cluster is running) is still gettting collateral in V2/V1 format, that's why I was getting  SGX_QL_PCK_CERT_CHAIN_ERROR.

I am closing this issue now and check with SGXDCAPAttestation team whether backward compatibility is supported. 

Thank you very much for providing the valuable information.

**Comment by veenasai2** [comment]
Hi,

I recently created a new AKS cluster and found this issue is no longer present. Means I am succesfully able to verify the out-of-proc mode quote with my own pccs server and sgx-default-qpl library. Based on my understanding az-dcap-client on the _host_ system where the container is running is updated to the latest az-dcap-client (which has default collateral v3). The aesmd service provided by sgx-quote-helper talks to this _host az-dcap-client_ and generates a quote which has default collateral as V3.    This sgx quote with V3 version is successfully verified using my own pccs server and sgx-default-qpl-library. 

**Just a quick check on this** "Is there any way one can get to know which version of az-dcap-client is installed on the _host_ system to which the aesmd is communicating for quote generation?" 

Thanks
