### ISSUE TITLE
Add regional awareness

### ISSUE THREAD

**Issue by sethmoo** [microsoft/Azure-DCAP-Client#3]
Currently, there is only a central cache location for all servers. We will be expanding to multiple geographies as Azure Confidential Computing expands.

The client must become for regionally-aware so we route requests to the correct endpoint.

**Comment by sethmoo** [comment]
Instead of using regional awareness, we'll instead rely on performance-based DNS routing.

Repurposing this issue to track the base URL/hostname change to the global endpoint that will be set up soon(ish). Tentative plan is end of month to have fault tolerance and automatic failover in place.

**Comment by deschuma** [comment]
This has been fixed - global endpoint has been up for a while
