### ISSUE TITLE
The file "configure" needs to have execute permission before it could be run

### ISSUE THREAD

**Issue by soccerGB** [Microsoft/Azure-DCAP-Client#4]
I hit this when trying to build this library on my devbox

~/azdcapclient/src/Linux$ ls -l
total 20
-rw-rw-r--  1  configure
drwxrwxr-x 2  debian
-rw-rw-r-- 1  init.cpp
-rw-rw-r-- 1  Makefile.in
-rw-rw-r-- 1  README.MD

I have to add execution permission before I could build it successfully.

**Comment by sethmoo** [comment]
Fixed in https://github.com/Microsoft/Azure-DCAP-Client/commit/5ed8767a50ece444621ef5b3bf234125a3e0fdc2
