### ISSUE TITLE
[local cache Linux] Throw more meaningful error in case the user has no home directory

### ISSUE THREAD

**Issue by stefanlupsa** [Microsoft/Azure-DCAP-Client#43]
Here: https://github.com/Microsoft/Azure-DCAP-Client/blob/23760512b07ed0314217aef3bb3bd26ef3a5c3b8/src/Linux/local_cache.cpp#L183-L205

There is a case where a user trying to run has no home directory (in this case a docker container that just uses the current context mounted in the container with az-dcap-client install) the `$HOME` environment variable will just be `"/"` which is not checked against, the check is only done against an empty `$HOME` and the folder .az-dcap-client the local_cache.cpp is trying to create has no write permissions in `"/"`, There should be either a more meaningful error or a mention in the documentation about this `$AZDCAPCACHE` environment variable.

This was previously not seen as we were running the containers with "-u root" option that didn't have an issue creating `"//.az-dcap-client"` folder. I've discovered this while working on #41 

@ionutbalutoiu told me another contributor complained that the testing inside the Dockerfile didn't work unless there was a user created inside the Dockerfile

@johnkord @andschwa i'm not sure how to handle this since it's on the .cpp / docs side and would like your feedback, on the Jenkins side we can just use` withEnv(["AZDCAPCACHE=${WORKSPACE}"])`

**Comment by ionutbalutoiu** [comment]
> There is a case where a user trying to run has no home directory (in this case a docker container that just uses the current context mounted in the container with az-dcap-client install) the `$HOME` environment variable will just be `"/"` which is not checked against, the check is only done against an empty `$HOME` and the folder .az-dcap-client the local_cache.cpp is trying to create has no write permissions in `"/"`, There should be either a more meaningful error or a mention in the documentation about this `$AZDCAPCACHE` environment variable.

I don't think we need to add extra code for checking if the location from `$HOME` has permissions to write / read files. The use case you described is encountered in the CI when some commands are executed under some `UID` and `GID` non-existent in the container.

Generally, in every Unix system, the `$HOME` should have permissions for the current user, unless something is wrong with the system.

However, I agree with documenting the `AZDCAPCACHE` variable, in case anybody needs it in the future.

**Comment by johnkord** [comment]
On a related note, this PR uses an environment variable too: 

https://github.com/Microsoft/Azure-DCAP-Client/pull/45/files#diff-6b5c5dfc409dac9819a2d768148d6ae1R173

We might want to standardize the envvar naming scheme for the Azure DCAP Client before we do a release!  I went with an "AZURE_" prefix, and I see this one uses an "AZDCAP" prefix.

I think I prefer the AZDCAP prefix, but perhaps with an underscore after it, like "AZDCAP_CACHE", and "AZDCAP_BASE_CERT_URL" in these cases.  What do you think about this? @ionutbalutoiu @stefanlupsa @soccerGB @msft-jonnadul

**Comment by msft-jonnadul** [comment]
> On a related note, this PR uses an environment variable too:
> 
> https://github.com/Microsoft/Azure-DCAP-Client/pull/45/files#diff-6b5c5dfc409dac9819a2d768148d6ae1R173
> 
> We might want to standardize the envvar naming scheme for the Azure DCAP Client before we do a release! I went with an "AZURE_" prefix, and I see this one uses an "AZDCAP" prefix.
> 
> I think I prefer the AZDCAP prefix, but perhaps with an underscore after it, like "AZDCAP_CACHE", and "AZDCAP_BASE_CERT_URL" in these cases. What do you think about this? @ionutbalutoiu @stefanlupsa @soccerGB @msft-jonnadul

Agreed, I'm leaning more towards AZDCAP_ than AZURE_ but we should absolutely standardize as well as update our documentation! @johnkord  can you incorporate this changes as part of your current PR? Thanks!

**Comment by ionutbalutoiu** [comment]
> On a related note, this PR uses an environment variable too:
> 
> https://github.com/Microsoft/Azure-DCAP-Client/pull/45/files#diff-6b5c5dfc409dac9819a2d768148d6ae1R173
> 
> We might want to standardize the envvar naming scheme for the Azure DCAP Client before we do a release! I went with an "AZURE_" prefix, and I see this one uses an "AZDCAP" prefix.
> 
> I think I prefer the AZDCAP prefix, but perhaps with an underscore after it, like "AZDCAP_CACHE", and "AZDCAP_BASE_CERT_URL" in these cases. What do you think about this? @ionutbalutoiu @stefanlupsa @soccerGB @msft-jonnadul

sounds good to me!

**Comment by johnkord** [comment]
I've incorporated the environment variable renaming into this PR: #45

**Comment by ionutbalutoiu** [comment]
> I've incorporated the environment variable renaming into this PR: #45

Maybe it's worth adding a new section in the `README.md` called `Configuration` and document this new environment variables.

**Comment by stefanlupsa** [comment]
> > I've incorporated the environment variable renaming into this PR: #45
> 
> Maybe it's worth adding a new section in the `README.md` called `Configuration` and document this new environment variables.

@ionutbalutoiu this is the main reason i opened the issue.
