### ISSUE TITLE
Missing newline in dcap_provider.cpp:build_cert_chain

### ISSUE THREAD

**Issue by jethrogb** [Microsoft/Azure-DCAP-Client#5]
The body returned by Intel from the "Get PCK Certificate" API does not end with a newline. In `build_cert_chain`, this body is concatenated with the certificate chain without adding a newline, resulting in an incorrectly-formatted certificate chain.

**Comment by sethmoo** [comment]
It appears that libcurl consistently appends a CRLF. Thus, the cert chain we build is actually correct.

I spent some time debugging into libcurl to see where it comes from, whether there was an option to control it, etc. However, I couldn't find much info.

Just in case, I added a handler in case some versions of libcurl do not append CRLF to the buffer: https://github.com/Microsoft/Azure-DCAP-Client/pull/6

**Comment by sethmoo** [comment]
Strange. I was testing on 18.04 and with latest sources from libcurl. The CRLF shows up consistently in my test output.

I'll hop on a 16.04 VM and poke around at it some more. At a minimum, my PR looks incorrect as it has Windows CRLF. I'll adjust as necessary.

**Comment by sethmoo** [comment]
One thing to note: this library does not download from the Intel service, but from the Azure cache. The Azure cache _does_ add the newline. This fact totally slipped my mind while debugging this issue.

**Comment by jethrogb** [comment]
But if the Azure service does add the newline, how did the chain end up without the newline?

**Comment by sethmoo** [comment]
I found the issue. It's not a discrepancy between services, but in the data in the back end storage.

In pre-production, the data stored on the back-end was different from production. Our internal unit tests were pointing at the pre-production certificates, and should have been redirected to the production data.

Fixing this involves three parts:
1. Fix the library to add the newline: https://github.com/Microsoft/Azure-DCAP-Client/pull/6
2. Update unit tests (done)
3. Flush pre-production data from the back-end (working on this).

**Comment by sethmoo** [comment]
Before I close this out... @jethrogb, are you seeing issues with quote validation?

**Comment by jethrogb** [comment]
I haven't tested that flow yet.

**Comment by sethmoo** [comment]
The Open Enclave folks are reporting things are working as-is in their stack.

I'm going to close this out for now. If you see any issues, please reach out and I'll turn the crank and get a new release out.
