### ISSUE TITLE
Add Windows testing stage to the CI Jenkinsfile

### ISSUE THREAD

**Issue by ionutbalutoiu** [microsoft/Azure-DCAP-Client#64]
If the project builds on Windows, we should update our CI Jenkinsfile by adding a new testing stage targeted against Windows platform.

**Comment by ionutbalutoiu** [comment]
How does this sound to you guys ?

**Comment by anitagov** [comment]
@ionutbalutoiu - From the Open Enclave side, we have not yet pushed the changes needed for DCAP libraries to work on Windows yet. Simon and I are still working on a branch.

**Comment by anitagov** [comment]
cc: @CodeMonkeyLeet

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu - From the Open Enclave side, we have not yet pushed the changes needed for DCAP libraries to work on Windows yet. Simon and I are still working on a branch.

Thanks for the info, @anitagov. 

My suggestion was about the [.jenkins/Jenkinsfile](https://github.com/microsoft/Azure-DCAP-Client/blob/df4d12d3204dfaf0a73771b59b2e9f8b974d37d0/.jenkins/Jenkinsfile) hosted in this repository.

We have a separate CI job running on master check-ins, and on every PR for the Azure-DCAP-Client repository. The Jenkinsfile from this repository contains only Linux stages to build + run unit tests on both Ubuntu 16.04 and Ubuntu 18.04.

Just by looking at the documentation, I think we can build Azure-DCAP-Client on Windows (I noticed [this](https://github.com/microsoft/Azure-DCAP-Client/tree/master/src/Windows#build)). And I also noticed commit https://github.com/microsoft/Azure-DCAP-Client/commit/c494fa64295cfaf3273dca8330f53107cb2a291c, which makes me think that maybe we can run unit tests as well.

So, I suggest adding an extra CI stage here to solely build + run unit tests on Windows for the Azure-DCAP-Client.

What do you think ?

**Comment by anitagov** [comment]
@ionutbalutoiu - The Azure-DCAP-Client on Windows build isn't automated and can currently be done manually using the Visual Studio 2017 IDE. There are a couple of outstanding issues with the build as I mentioned in the issue (https://github.com/microsoft/Azure-DCAP-Client/issues/62) that I filed recently. 
To get an automated build, a new script will be required. 

I am not sure if the unit tests are meant for Linux or for Linux and Windows.

Another important gap is that we still do not have attestation portion completed from OE and Azure-DCAP-Client for Windows.

But automated build is a minimum requirement for initiating CI.

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu - The Azure-DCAP-Client on Windows build isn't automated and can currently be done manually using the Visual Studio 2017 IDE. There are a couple of outstanding issues with the build as I mentioned in the issue (#62) that I filed recently.
> To get an automated build, a new script will be required.

So far, we have the following WiP [pull request #65](https://github.com/microsoft/Azure-DCAP-Client/pull/65) to simply build the project.

We will also take a look at issue https://github.com/microsoft/Azure-DCAP-Client/issues/62 reported by you.

> 
> I am not sure if the unit tests are meant for Linux or for Linux and Windows.
> 
> Another important gap is that we still do not have attestation portion completed from OE and Azure-DCAP-Client for Windows.

Once this part is finished, I believe running some kind of tests on Windows will make more sense.

> 
> But automated build is a minimum requirement for initiating CI.

I believe that the changes to the Jenkinsfile from [PR-65](https://github.com/microsoft/Azure-DCAP-Client/pull/65) should include everything needed to have an automated build on Windows via Visual Studio.

What do you think ?

**Comment by anitagov** [comment]
Can you have a script do these steps and then invoke this in the Jenkins scripts? This is because developers can use this script to build. Thanks.

**Comment by CodeMonkeyLeet** [comment]
@ionutbalutoiu I think it's worth trying to do this, but there are a couple of additional caveats that extend beyond the Jenkins file:

- The Ansible configuration for Windows we have set up in the OE SDK repo is different from the expectations of the vcxproj here (e.g. path with full nuget package version)

- The vcxproj file does not appear to build the UnitTests folder yet. They may work on Windows, but they do not appear to be integrated into Windows build project by default

**Comment by anitagov** [comment]
cc @soccerGB

**Comment by ionutbalutoiu** [comment]
> Can you have a script do these steps and then invoke this in the Jenkins scripts? This is because developers can use this script to build. Thanks.

@anitagov That's a good idea! We'll be adding a new script `build.ps1`, and one can simply execute that and build the project on Windows.

> @ionutbalutoiu I think it's worth trying to do this, but there are a couple of additional caveats that extend beyond the Jenkins file:
> 
> * The Ansible configuration for Windows we have set up in the OE SDK repo is different from the expectations of the vcxproj here (e.g. path with full nuget package version)

@CodeMonkeyLeet I think that executing `get-prereqs.ps1` PowerShell script + `nuget.exe restore` is enough to have the project built via Visual Studio 2017 on Windows as done in the PR https://github.com/microsoft/Azure-DCAP-Client/pull/65.

However, the Azure-DCAP-Client project targets the SDK `10.0.17134.0`:
https://github.com/microsoft/Azure-DCAP-Client/blob/c494fa64295cfaf3273dca8330f53107cb2a291c/src/Windows/dcap_provider.vcxproj#L18

and we had to add this when installing Visual Studio in the Ansible scripts. This is the [pull request](https://github.com/microsoft/openenclave/pull/1846) to OE with this change.

> * The vcxproj file does not appear to build the UnitTests folder yet. They may work on Windows, but they do not appear to be integrated into Windows build project by default

I suppose we can add the UnitTests later on, and see if they work.

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/microsoft/Azure-DCAP-Client/pull/65

**Comment by anitagov** [comment]
> > Can you have a script do these steps and then invoke this in the Jenkins scripts? This is because developers can use this script to build. Thanks.
> 
> @anitagov That's a good idea! We'll be adding a new script `build.ps1`, and one can simply execute that and build the project on Windows.
> 

@ionutbalutoiu - This is great. Thanks.
