### ISSUE TITLE
Default location for cache directory when $HOME isn't defined

### ISSUE THREAD

**Issue by achamayou** [microsoft/Azure-DCAP-Client#66]
In some contexts, eg. containers, applictions are deliberately run with a minimal environment, something without a defined $HOME.

Would it be possible to default to /var/cache/ in those contexts? This is reasonably common: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html.

**Comment by deschuma** [comment]
If we try and use /var/cache/ won't we run into permissions issues? 

Currently if home is not defined an exception will be thrown and user can choose to either define AZDCAPCACHE or HOME.

**Comment by achamayou** [comment]
@deschuma you are right, /var/cache is meant for system-wide caching but is typically only accessible to processes running with super-user privileges.

The most standard thing I can find for unprivileged code is this: https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

This doesn't really help when there's no $HOME. I think the safest thing to do is to look for TMPDIR next (https://en.wikipedia.org/wiki/TMPDIR), that stands a very good chance of being defined, and at worst /tmp.

**Comment by deschuma** [comment]
Awesome! I don't see XDG_CACHE_HOME defined in the acc vm but what we can do is try the following locations for caching:
1) If environment variable is set, use that
2) If XDG_CACHE_HOME environment variable is set, use that
3) If the HOME environment variable is set, use that
4) Fallback to the tmp directory

My PR already deals with the case where permissions fail for whatever reason - dcap will emit a warning and will still function, just without caching so I'll just roll this fix in with that one.

**Comment by deschuma** [comment]
This is addressed here: https://github.com/microsoft/Azure-DCAP-Client/pull/97
