### ISSUE TITLE
Publish the Azure-DCAP-Client Windows nupkg file 

### ISSUE THREAD

**Issue by ionutbalutoiu** [microsoft/Azure-DCAP-Client#74]
The Open Enclave Ansible scripts to setup the environments for developers install the `Microsoft.Azure.DCAP.Client.1.0.0.nupkg` file:
https://github.com/openenclave/openenclave/blob/d5fb0a9f6a2c4b614126f1a747be89b1d7d754dc/scripts/ansible/roles/windows/az-dcap-client/vars/windows.yml#L8

However, currently, the file consumed is hosted in the Azure Open Enclave storage account:
https://oejenkins.blob.core.windows.net/oejenkins

It would be advisable to have this file downloaded from official GitHub releases of this project:
https://github.com/Microsoft/Azure-DCAP-Client/releases

So far, only an `amd64.tar.gz` archive with a Linux build is attached to the `1.0` release.

**Comment by deschuma** [comment]
@ionutbalutoiu  we publish the Windows nuget package here: https://www.nuget.org/packages/Azure.DCAP.Windows/0.0.3

**Comment by ionutbalutoiu** [comment]
@deschuma The `nuget` package linked by you is version `0.0.3`. The latest release for the `Azure-DCAP-Client` is `1.1`. Shouldn't this be published to `nuget` already ?

**Comment by deschuma** [comment]
Please see the latest version published on nuget: https://www.nuget.org/packages/Azure.DCAP.Windows/

I also included the package in the latest github release

**Comment by ionutbalutoiu** [comment]
@deschuma 

All good! The `nuget.org` source works as well. Thanks!

Closing this issue.
