### ISSUE TITLE
Root cert validation is not working correctly

### ISSUE THREAD

**Issue by sethmoo** [Microsoft/Azure-DCAP-Client#8]
The root cert, as passed to `curl_easy::create` is not being checked as a valid root for https connections.

It appears we have a bug in `ssl_context_callback`. Address this and add a negative test case to ensure we don't run across this again in the future.

**Comment by soccerGB** [comment]
I took a look at the curl_easy class implementation. It looks like the ca_certparameter passed in the call to curl_easy::create(intel_cert_base_url, ca_cert) was used as the client's cert, which was handled in ssl_context_callback.

To validate server's certificate, 

// verify the server's SSL certificate, we can add the following two CURL options in the easy_curl implementation to enable checking on the server certificate and host name

    // verify the server's SSL certificate
    easy->set_opt_or_throw(CURLOPT_SSL_VERIFYPEER, 1L);
    // verify server certificate's name against host
    easy->set_opt_or_throw(CURLOPT_SSL_VERIFYHOST, 2L);

**Comment by sethmoo** [comment]
You also need the code in `ssl_context_callback` to setup the root cert store. It just looks like the correct SSL verify options weren't also set.

**Comment by sethmoo** [comment]
It turns out we didn't have a problem here. There is a default root cert store for libcurl, and the necessary roots are included.
