### ISSUE TITLE
Local caching of collaterals in Azure DCAP client

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/Azure-DCAP-Client#88]
Opening this issue in order to keep track of the offline request.

Currently the collaterals, QE identity info and Revocation info are not cached, only the PCK Cert is cached.  In order to improve performance, caching for these is needed.  For more information please see https://github.com/openenclave/openenclave/issues/2283.

**Comment by deschuma** [comment]
This has been fixed - please feel free to re-open if needed
