### ISSUE TITLE
Local cache file permission issue

### ISSUE THREAD

**Issue by yentsanglee** [microsoft/Azure-DCAP-Client#98]
Due to caller privilege change, previously cached file cannot be accessed from subsequent calls. Specifically, local_cache_add() call from sgx_ql_get_quote_config() in dcap_provider.cpp throws exception because file access permission denied. This causes sgx_ql_get_quote_config() to return error.

Issues:
1. Local cache can be shared by all users. It should be in a folder/file that's accessible to all.
2. Caching failure should not be a fatal operation. After all, the mission of sgx_ql_get_quote_config() is to retrieve certificate.

**Comment by achamayou** [comment]
@yentsanglee agreed, I have suggest /var/cache for this before (#66). If the cache is created with broad permissions, it should work for all users (synchronisation must be implemented, but that's also true for a per-user cache anyway).

The code and the cache is untrusted, so from a security perspective, this should be fine too.

**Comment by deschuma** [comment]
Thanks! I'm working on #2 - lack of caching should not be a fatal error

In terms of having some other folder to put collateral do you have other suggestion? 
/var/cache is not accessible to the user on our ACC VM:
derek@accTestVMUbuntu18:/$ mkdir /var/cache/.az_dcap_client
mkdir: cannot create directory ‘/var/cache/.az_dcap_client’: Permission denied

I've tried hunting for other locations but the users' home directory seems generally like the right place - For other scenarios what do we think about depending on the users or whoever is delivering Azure DCAP Client to setup the environment variable correctly?

**Comment by achamayou** [comment]
@deschuma I've answer in #66, sorry, in short I would suggest $TMPDIR, or if that's also missing /tmp. I do agree that .cache/az_dcap_client or .az_dcap_client under $HOME is a reasonable first choice.

**Comment by deschuma** [comment]
This is addressed here: https://github.com/microsoft/Azure-DCAP-Client/pull/97

**Comment by achamayou** [comment]
@deschuma thank you!

**Comment by deschuma** [comment]
@yentsanglee Do you have a way to confirm this is fixed and close?

**Comment by yentsanglee** [comment]
Confirmed. Thanks for the fix in v1.4.
