### ISSUE TITLE
Incorrect Jenkins Labels

### ISSUE THREAD

**Issue by BRMcLaren** [microsoft/Azure-DCAP-Client#99]
I was noticing that on the Jenkins server VM's are failing to spawn. This is due to the Jenkins labels being outdated.

Over in OpenEnclave, the labels to spawn a "SGXFLC-Window" VM are "SGXFLC-Windows-2016-DCAP"  and "SGXFLC-Windows-2019-DCAP" dependant on needs. "SGXFLC-Window" was removed when 2019 support was added.

**Comment by deschuma** [comment]
This is addressed here: https://github.com/microsoft/Azure-DCAP-Client/pull/97
